config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'posts#index'
  resources :posts do
    resources :comments, except: :show
  end


  resources :categories, except: :show
  namespace :user do
    resources :posts
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships
  has_many :post_category_ships, dependent: :restrict_with_error
  has_many :posts, through: :post_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, :address, presence: true
  # has_many :comments
  has_many :comments, dependent: :destroy
  has_many :post_category_ships,dependent: :destroy
  has_many :categories, through: :post_category_ships
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created successfully'
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated successfully'
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    if@category.destroy
    flash[:notice] = 'Category deleted successfully'
    redirect_to categories_path
    else
      flash[:alert] = 'Failed'
      redirect_to categories_path
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :validate_comment_owner, only: [:edit, :update, :destroy]

  def index
    # @comments = @post.comments.includes(:user)
    @comments = @post.comments.includes(:user).all.page(params[:page]).per(5)
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully'
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to post_comments_path(@post)
    else
      flash[:alert] = 'Failed'
      redirect_to post_comments_path(@post)
    end
  end


  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def validate_comment_owner
    unless @comment.user == current_user
      flash[:notice] = 'the comment not belongs to you'
      redirect_to post_comments_path(@post)
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :validate_post_owner, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories).all.order(comments_count: :desc).page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def show;
    session[:previous_url] = request.referer
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post updated successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      flash[:notice] = 'Post destroyed successfully'
      redirect_to posts_path
    else
      flash[:alert] = @post.errors.full_messages.join(", ")
      redirect_to posts_path
    end

  end


  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :address,:image, category_ids: [])
  end

  def validate_post_owner
    unless @post.user == current_user
      flash[:notice] = 'the post not belongs to you'
      redirect_to posts_path
    end
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @my_comments = current_user.comments.includes(:post).order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
    before_action :authenticate_user!

    def index
      @user_posts = current_user.posts.page(params[:page]).per(5)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>
<%= link_to 'back', categories_path %>

app/views/categories/edit.html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form',
           locals: { category: @category,
                     path: category_path(@category) } %>

app/views/categories/index.html.erb
<h1>Category</h1>
<%= link_to 'new', new_category_path, class: 'btn btn-outline-dark' %>
<hr>
<ul>
  <% @categories.each do |category| %>
    <li><%= category.name %></li>
    <%= link_to :edit, edit_category_path(category), class: 'btn btn-outline-dark'%>
    <%= button_to :delete, category_path(category), method: :delete %>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, method: method, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %></h1>
<h2>Edit Comment ID: <%= @comment.id %></h2>
<%= render partial: 'form', locals: { comment: @comment, path: post_comment_path(@post, @comment), method: :patch } %>
<%= link_to 'Back', post_comments_path, class: 'btn btn-outline-dark' %>

app/views/comments/index.html.erb
<h1>Title <%= @post.title %></h1>
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= "#{comment.user&.email}"%> "<%= comment.content %>" <%="#{comment.created_at.strftime("Commented on %m/%d/%Y at %I:%M%p")}" %>
      <% if user_signed_in? && comment.user == current_user %>
        <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment), class: "btn btn-sm btn-warning" %>
        <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete, class: "btn btn-sm btn-danger" %>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back', posts_path, class: 'btn btn-outline-dark'%>
<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-dark' %>

<%= paginate @comments %>

app/views/comments/new.html.erb
<%= render partial: 'form', locals: { comment: @comment, path: post_comments_path(@post), method: :post } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DISASTER</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light" bg-light style="background-color: #e3f2fd;">

    <div class="container-fluid">
      <%= link_to "KODACAMP", root_path, class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav e-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'My Posts', user_posts_path, class: "nav-link #{'active' if
              controller_name == 'user/posts' && action_name == 'index'}", 'aria-current': 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My comments', user_comments_path, class: "nav-link #{'active' if
              controller_name == 'user/comments' && action_name == 'index'}", 'aria-current': 'page' %>
          </li>
          <% if user_signed_in? %>
            <%= button_to 'Sign out', destroy_user_session_path,
                          style: "color: red;", method: :delete,
                          data: { confirm: 'Are you sure you want to logout' } %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link', style: "color: green;" %>
          <% end %>
          </li>
        </ul>
      </div>

    </div>
  </nav>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <p class="notice"><%= alert %></p>
      </div>
    <% end %>
  </div>

  </body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <% if post.errors.any? %>
    <div class="alert alert-warning" role="alert">
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="container">
<%= form_with model: post do |form| %>
  <% if post.errors.any? %>
    <ul>
      <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name, class: 'form-control' %>
  </div>
    <div>
      <%= form.file_field :image%>
    </div>
  <%= form.submit class: 'btn btn-primary'%>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render partial: 'posts/form',
           locals: { url: post_path(@post), method: :patch, post: @post } %>

app/views/posts/index.html.erb
<h1>Hello <%= current_user.email if user_signed_in? %></h1>
<h2>Post List</h2>
<%= link_to 'New', new_post_path, class: 'btn btn-success btn-sm' %>
<table class="table table-hover table-bordered">
  <thead class="table-dark">
  <td>title</td>
  <td>content</td>
  <td>comments count</td>
  <td>image</td>
  <td>address</td>
  <td>Category</td>
  <td>user</td>
  <td>Actions</td>
  </thead>
  <% @posts.each_with_index do |post, index| %>
    <tr>
      <td>
        <% if index < 3 && params[:page] == nil %>
          <span class="badge rounded-pill bg-warning text-dark">HOT</span>
        <% end %>
        <%= post.title %>
      </td>
      <td><%= post.content %></td>
      <td><%= post.comments_count %></td>
      <td><%= image_tag post.image.url, style: "width: 100px; height: 100px;" if post.image.present? %></td>
      <td><%= post.address %></td>
      <td><%= post.categories.pluck(:name).join(',') %></td>
      <td><%= post.user&.email %></td>
      <td>
        <%= link_to 'Show', post_path(post) %>
        <%= link_to 'Comments', post_comments_path(post) %>
        <%= link_to 'New Comment', new_post_comment_path(post) %>
        <% if user_signed_in? && post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= button_to 'Delete', post_path(post), method: :delete %>
        <% end %>
      </td>
    </tr>
    <% end %>
</table>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render partial: 'posts/form',
           locals: { url: posts_path, method: :post, post: @post } %>

app/views/posts/show.html.erb
<h1>show post id: <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
  <li><%= @post.address %></li>
  <li>Created BY: <%= @post.user&.email %></li>
</ul>
<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-dark' %>
<%= link_to 'Edit', edit_post_path, class: 'btn btn-dark' %>
<hr>
<h2>Comments </h2>
<ul>
<% @post.comments.each do|comment| %>
     <%= "#{comment.user&.email}"%> "<%= comment.content %>"
     <%="#{comment.created_at.strftime("Commented on %m/%d/%Y at %I:%M%p")}" %>
<% end %>
</ul>
<br>
<%= link_to 'GO BACK', session[:previous_url] || user_posts_path %>

app/views/user/comments/index.html.erb
<h1>Your Comments</h1>

<table>
  <% @my_comments.each do |comment| %>
    <li><%= comment.content %></li>
    <%= link_to 'VIEW POST', post_path(comment.post) %>
  <% end %>
</table>

<%= paginate @my_comments %>

app/views/user/posts/index.html.erb
<h1>Your Posts</h1>

<table class="table table-hover table-bordered">
  <thead class="table-dark">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Category</th>
    <th>Address</th>
    <th>Action</th>

  </tr>
  </thead>

  <% @user_posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.categories.pluck(:name).join(',') %></td>
      <td><%= post.address %></td>
      <td class="btn-group-vertical">
        <%= link_to 'Show', post_path(post), class: "btn btn-outline-primary" %>
          <%= link_to 'Edit', edit_post_path(post.id), class: "btn btn-outline-success" %>
          <%= link_to 'New Comment', new_post_comment_path(post.id), class: "btn btn-outline-secondary" %>
          <%= button_to 'Delete', post_path(post.id), method: :delete, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @user_posts %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="container">

  <h1>Hello <%= current_user.email if user_signed_in? %></h1>
  <h2>News Today</h2>
  <hr>
  <h5>News Lists</h5>
</div>